#The default BoneTool wand material
toolMaterial: BONE
#If you have Builder's Utilities installed, BoneTool will take over it's /blocks menu and put it's own. If you are not comfortable with this, you can disable it here.
takeOverBUtilSecretBlocks: true
#This allows adding colors on signs using &
allowColorOnSign: true
#If you want to blacklist some specific tools, add them here
#Look below for a list of Tools
toolBlacklist: []
#This adds the option to change light level to blocks. LightAPI is required. Kinda useless since light blocks exists (>=1.17)
LightAPI: false
#If using PlotSquared, players will only be able to use the tool inside a plot. If you want players to be able to use the tool outside of plot worlds/areas, you can turn this on.
allowOutsidePlotArea: false
#Default language to be used by BoneTool
#Failure to load the language file will fallback to english
#Check out readme.txt in the locale folder for more info
defaultLocale: en

#Fly Speed
#If you want to limit fly speeds on the server for whatever reason, you can do it here
#0.1 is normal speed, 1 is the maximum regardless of what you set. 0 is also the minimum (literally can't move at 0)
minFlySpeed: 0
maxFlySpeed: 1

#Secret/Illegal Blocks
#You can disable them here if a specific one causes problems for you server.

#SpecialItems: 
netherPortal: true
endPortal: true
pistonHead: true
doubleLadder: true
litRedstoneLamp: true
endGateway: true
paintingByName: true
#Unobtainable items:
commandBlocks: true
commandBlockMinecart: true
sculkSensor: true
jigsaw: true
debugStick: true
spawner: true
barrier: true
structureVoid: true
dragonEgg: true
structureBlock: true
lightBlock: true
invisFrame: true

#Spawner Configs
#This decides how high a config can be set for a spawner.
#You can also blacklist some entities.
#Use the EntityType name to disable a mob
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
entityBlacklist: ['PLAYER', 'DROPPED_ITEM', 'BLOCK_DISPLAY', 'MARKER', 'INTERACTION', 'ITEM_DISPLAY', 'TEXT_DISPLAY']
spawnerDelay: 10000
maxNearbyEntities: 1000
minSpawnDelay: 10000
maxSpawnDelay: 10000
reqPlayerRange: 300
spawnCount: 100
spawnRange: 300

#Tool name for blacklisting:
#toolBlacklist: ['AGEABLE', 'ANALOGUEPOWERABLE', 'ATTACHABLE', 'BAMBOO', 'BEACON', 'BED', 'BISECTED', 'CAKE', 'COLOR', 'DEBUG', 'DIRECTIONAL', 'FACEATTACHABLE', 'HONEY', 'LEVELLED', 'LIGHTABLE', 'LIGHTAPI', 'MULTIPLEFACING', 'NONE', 'NOTEBLOCK', 'OPENABLE', 'ORIENTABLE', 'PLAYERFACE', 'POT', 'POWERABLE', 'RAIL', 'ROTATABLE', 'RESPAWNANCHOR', 'SIGN', 'SNOWABLE', 'SPAWNER', 'WATERLOGGED'] (There's a lot of tools and I'm too lazy to write them all)
