name: BoneTool
main: net.dezilla.bonetool.ToolMain
version: 1.1.1
api-version: 1.13
website: https://www.dezilla.net/
dev-url: https://www.dezilla.net/
description: A tool for editing block properties and more.
authors: [DeZilla]
softdepend: [Builders-Utilities, LightAPI, PlotSquared]
